import { Match, Player } from './types';

/**
 * 2026 Wimbledon Gentlemen's Singles — official main draw (128 players).
 * Source: Wimbledon 2026 draw sheet (last updated 28 Jun 2026).
 * Players are listed in draw order; consecutive pairs form the 64 R1 matches.
 */
export const DRAW_ORDER: Player[] = [
  { name: 'Jannik SINNER', country: 'ITA', seed: 1 },
  { name: 'Miomir KECMANOVIC', country: 'SRB' },
  { name: 'Nuno BORGES', country: 'POR' },
  { name: 'Tristan BOYER', country: 'USA', status: 'Q' },
  { name: 'Aleksandar VUKIC', country: 'AUS' },
  { name: 'Jenson BROOKSBY', country: 'USA' },
  { name: 'Emilio NAVA', country: 'USA' },
  { name: 'Ignacio BUSE', country: 'PER', seed: 31 },
  { name: 'Rafael JODAR', country: 'ESP', seed: 23 },
  { name: 'Felix GILL', country: 'GBR', status: 'W' },
  { name: 'Denis SHAPOVALOV', country: 'CAN' },
  { name: 'Pablo CARRENO BUSTA', country: 'ESP' },
  { name: 'Shintaro MOCHIZUKI', country: 'JPN', status: 'Q' },
  { name: 'Max BASING', country: 'GBR', status: 'Q' },
  { name: 'Ethan QUINN', country: 'USA' },
  { name: 'Luciano DARDERI', country: 'ITA', seed: 14 },
  { name: 'Casper RUUD', country: 'NOR', seed: 11 },
  { name: 'Hubert HURKACZ', country: 'POL' },
  { name: 'Hamad MEDJEDOVIC', country: 'SRB' },
  { name: 'Sebastian OFNER', country: 'AUT' },
  { name: 'Soonwoo KWON', country: 'KOR', status: 'Q' },
  { name: 'Martin LANDALUCE', country: 'ESP' },
  { name: 'Alexandre MULLER', country: 'FRA' },
  { name: 'Tommy PAUL', country: 'USA', seed: 21 },
  { name: 'Brandon NAKASHIMA', country: 'USA', seed: 28 },
  { name: 'Jack PINNINGTON JONES', country: 'GBR', status: 'W' },
  { name: 'Jan-Lennard STRUFF', country: 'GER' },
  { name: 'Sebastian BAEZ', country: 'ARG' },
  { name: 'Camilo UGO CARABELLI', country: 'ARG' },
  { name: 'Daniel MERIDA', country: 'ESP' },
  { name: 'Marin CILIC', country: 'CRO' },
  { name: 'Daniil MEDVEDEV', country: '---', seed: 8 },
  { name: 'Felix AUGER-ALIASSIME', country: 'CAN', seed: 3 },
  { name: 'Aleksandr SHEVCHENKO', country: 'KAZ' },
  { name: 'Adam WALTON', country: 'AUS' },
  { name: 'Dino PRIZMIC', country: 'CRO' },
  { name: 'Adolfo Daniel VALLEJO', country: 'PAR', status: 'Q' },
  { name: 'Nicolas MEJIA', country: 'COL', status: 'Q' },
  { name: 'Michael ZHENG', country: 'USA' },
  { name: 'Cameron NORRIE', country: 'GBR', seed: 26 },
  { name: 'Alejandro DAVIDOVICH FOKINA', country: 'ESP', seed: 22 },
  { name: 'Juan Manuel CERUNDOLO', country: 'ARG' },
  { name: 'Thiago Agustin TIRANTE', country: 'ARG' },
  { name: 'Fabian MAROZSAN', country: 'HUN' },
  { name: 'Luca VAN ASSCHE', country: 'FRA' },
  { name: 'Marton FUCSOVICS', country: 'HUN' },
  { name: 'Dalibor SVRCINA', country: 'CZE' },
  { name: 'Learner TIEN', country: 'USA', seed: 16 },
  { name: 'Andrey RUBLEV', country: '---', seed: 12 },
  { name: 'Roman SAFIULLIN', country: '---', status: 'Q' },
  { name: 'Aleksandar KOVACEVIC', country: 'USA' },
  { name: 'Botic VAN DE ZANDSCHULP', country: 'NED' },
  { name: 'Jesper DE JONG', country: 'NED' },
  { name: 'Rinky HIJIKATA', country: 'AUS' },
  { name: 'Roberto BAUTISTA AGUT', country: 'ESP' },
  { name: 'Joao FONSECA', country: 'BRA', seed: 24 },
  { name: 'Arthur RINDERKNECH', country: 'FRA', seed: 25 },
  { name: 'Oliver TARVET', country: 'GBR', status: 'Q' },
  { name: 'Marco TRUNGELLITI', country: 'ARG' },
  { name: 'Martin DAMM', country: 'USA' },
  { name: 'Hugo GASTON', country: 'FRA', status: 'Q' },
  { name: 'Stefanos TSITSIPAS', country: 'GRE' },
  { name: 'Yibing WU', country: 'CHN' },
  { name: 'Novak DJOKOVIC', country: 'SRB', seed: 7 },
  { name: 'Alex DE MINAUR', country: 'AUS', seed: 5 },
  { name: 'Roman Andres BURRUCHAGA', country: 'ARG' },
  { name: 'Adrian MANNARINO', country: 'FRA' },
  { name: 'Titouan DROGUET', country: 'FRA' },
  { name: 'Pablo LLAMAS RUIZ', country: 'ESP', status: 'L' },
  { name: 'Zachary SVAJDA', country: 'USA' },
  { name: 'Kamil MAJCHRZAK', country: 'POL' },
  { name: 'Alejandro TABILO', country: 'CHI', seed: 30 },
  { name: 'Karen KHACHANOV', country: '---', seed: 19 },
  { name: 'Billy HARRIS', country: 'GBR', status: 'Q' },
  { name: 'Yannick HANFMANN', country: 'GER' },
  { name: 'Giovanni MPETSHI PERRICARD', country: 'FRA' },
  { name: 'Tallon GRIEKSPOOR', country: 'NED' },
  { name: 'James DUCKWORTH', country: 'AUS' },
  { name: 'Mariano NAVONE', country: 'ARG' },
  { name: 'Flavio COBOLLI', country: 'ITA', seed: 9 },
  { name: 'Jakub MENSIK', country: 'CZE', seed: 15 },
  { name: 'Toby SAMUEL', country: 'GBR', status: 'W' },
  { name: 'Dane SWEENY', country: 'AUS', status: 'Q' },
  { name: 'Grigor DIMITROV', country: 'BUL', status: 'W' },
  { name: 'Stan WAWRINKA', country: 'SUI', status: 'W' },
  { name: 'Matteo BERRETTINI', country: 'ITA' },
  { name: 'Raphael COLLIGNON', country: 'BEL' },
  { name: 'Arthur FILS', country: 'FRA', seed: 20 },
  { name: 'Ugo HUMBERT', country: 'FRA', seed: 27 },
  { name: 'Zizou BERGS', country: 'BEL' },
  { name: 'Sho SHIMABUKURO', country: 'JPN' },
  { name: 'Jaime FARIA', country: 'POR', status: 'Q' },
  { name: 'Damir DZUMHUR', country: 'BIH' },
  { name: 'Arthur FERY', country: 'GBR', status: 'W' },
  { name: 'Otto VIRTANEN', country: 'FIN', status: 'Q' },
  { name: 'Ben SHELTON', country: 'USA', seed: 4 },
  { name: 'Taylor FRITZ', country: 'USA', seed: 6 },
  { name: 'Jack DRAPER', country: 'GBR' },
  { name: 'Patrick KYPSON', country: 'USA' },
  { name: 'Mackenzie MCDONALD', country: 'USA', status: 'Q' },
  { name: 'Benjamin BONZI', country: 'FRA' },
  { name: 'Gabriel DIALLO', country: 'CAN' },
  { name: 'Lorenzo SONEGO', country: 'ITA' },
  { name: 'Tomas Martin ETCHEVERRY', country: 'ARG', seed: 29 },
  { name: 'Frances TIAFOE', country: 'USA', seed: 17 },
  { name: 'Terence ATMANE', country: 'FRA' },
  { name: 'Vit KOPRIVA', country: 'CZE' },
  { name: 'Jan CHOINSKI', country: 'GBR' },
  { name: 'Kyrian JACQUET', country: 'FRA', status: 'Q' },
  { name: 'Vilius GAUBAS', country: 'LTU', status: 'Q' },
  { name: 'Thanasi KOKKINAKIS', country: 'AUS' },
  { name: 'Alexander BUBLIK', country: 'KAZ', seed: 10 },
  { name: 'Jiri LEHECKA', country: 'CZE', seed: 13 },
  { name: 'Alexei POPYRIN', country: 'AUS' },
  { name: 'Alex MOLCAN', country: 'SVK' },
  { name: 'Daniel ALTMAIER', country: 'GER' },
  { name: 'Alex MICHELSEN', country: 'USA' },
  { name: 'Jacob FEARNLEY', country: 'GBR', status: 'W' },
  { name: 'Jaume MUNAR', country: 'ESP' },
  { name: 'Francisco CERUNDOLO', country: 'ARG', seed: 18 },
  { name: 'Matteo ARNALDI', country: 'ITA', seed: 32 },
  { name: 'Quentin HALYS', country: 'FRA' },
  { name: 'Corentin MOUTET', country: 'FRA' },
  { name: 'Marcos GIRON', country: 'USA' },
  { name: 'Valentin ROYER', country: 'FRA' },
  { name: 'Harry WENDELKEN', country: 'GBR', status: 'W' },
  { name: 'Alexander BLOCKX', country: 'BEL' },
  { name: 'Alexander ZVEREV', country: 'GER', seed: 2 },
];

export function buildRound1Matches(): Match[] {
  if (DRAW_ORDER.length !== 128) {
    throw new Error(`Expected 128 players, got ${DRAW_ORDER.length}`);
  }
  const matches: Match[] = [];
  for (let i = 0; i < 64; i++) {
    matches.push({
      id: `r1-m${i + 1}`,
      round: 1,
      position: i + 1,
      player1: DRAW_ORDER[i * 2],
      player2: DRAW_ORDER[i * 2 + 1],
      nextMatchId: `r2-m${Math.floor(i / 2) + 1}`,
    });
  }
  return matches;
}
